"""MQ 配置子包。"""

from app.core.mq.config.common import (
    has_rabbitmq_url_configured,
    is_aio_pika_installed,
    is_chunk_add_consumer_enabled,
    is_chunk_rebuild_consumer_enabled,
    is_import_consumer_enabled,
)
from app.core.mq.config.document import (
    CHUNK_EDIT_LATEST_VERSION_KEY_PREFIX,
    ChunkAddRabbitMQSettings,
    ChunkRebuildRabbitMQSettings,
    IMPORT_LATEST_VERSION_KEY_PREFIX,
    ImportRabbitMQSettings,
    get_chunk_add_settings,
    get_chunk_rebuild_settings,
    get_import_settings,
)
from app.core.mq.config.topology import (
    MQ_EXCHANGE_KNOWLEDGE_CHUNK_ADD,
    MQ_EXCHANGE_KNOWLEDGE_CHUNK_REBUILD,
    MQ_EXCHANGE_KNOWLEDGE_IMPORT,
    MQ_QUEUE_CHUNK_ADD_COMMAND,
    MQ_QUEUE_CHUNK_REBUILD_COMMAND,
    MQ_QUEUE_IMPORT_COMMAND,
    MQ_ROUTING_KEY_CHUNK_ADD_COMMAND,
    MQ_ROUTING_KEY_CHUNK_ADD_RESULT,
    MQ_ROUTING_KEY_CHUNK_REBUILD_COMMAND,
    MQ_ROUTING_KEY_CHUNK_REBUILD_RESULT,
    MQ_ROUTING_KEY_IMPORT_COMMAND,
    MQ_ROUTING_KEY_IMPORT_RESULT,
)

__all__ = [
    "ChunkAddRabbitMQSettings",
    "get_chunk_add_settings",
    "ChunkRebuildRabbitMQSettings",
    "CHUNK_EDIT_LATEST_VERSION_KEY_PREFIX",
    "get_chunk_rebuild_settings",
    "ImportRabbitMQSettings",
    "IMPORT_LATEST_VERSION_KEY_PREFIX",
    "get_import_settings",
    "has_rabbitmq_url_configured",
    "is_aio_pika_installed",
    "is_chunk_add_consumer_enabled",
    "is_chunk_rebuild_consumer_enabled",
    "is_import_consumer_enabled",
    "MQ_EXCHANGE_KNOWLEDGE_CHUNK_ADD",
    "MQ_EXCHANGE_KNOWLEDGE_CHUNK_REBUILD",
    "MQ_EXCHANGE_KNOWLEDGE_IMPORT",
    "MQ_QUEUE_CHUNK_ADD_COMMAND",
    "MQ_QUEUE_CHUNK_REBUILD_COMMAND",
    "MQ_QUEUE_IMPORT_COMMAND",
    "MQ_ROUTING_KEY_CHUNK_ADD_COMMAND",
    "MQ_ROUTING_KEY_CHUNK_ADD_RESULT",
    "MQ_ROUTING_KEY_CHUNK_REBUILD_COMMAND",
    "MQ_ROUTING_KEY_CHUNK_REBUILD_RESULT",
    "MQ_ROUTING_KEY_IMPORT_COMMAND",
    "MQ_ROUTING_KEY_IMPORT_RESULT",
]
