"""
兼容层：MongoDB 数据库客户端入口已迁移至 `app.core.database.mongodb`。

保留本模块是为了避免历史导入路径在重构阶段立即失效。
"""

from app.core.database.mongodb import (
    DEFAULT_CONVERSATIONS_COLLECTION,
    DEFAULT_CONVERSATION_SUMMARIES_COLLECTION,
    DEFAULT_MESSAGES_COLLECTION,
    DEFAULT_MESSAGE_TRACES_COLLECTION,
    DEFAULT_MESSAGE_TTS_USAGES_COLLECTION,
    DEFAULT_MONGODB_DB_NAME,
    DEFAULT_MONGODB_STARTUP_PING_ENABLED,
    DEFAULT_MONGODB_TIMEOUT_MS,
    DEFAULT_MONGODB_URI,
    get_mongo_client,
    get_mongo_database,
    verify_mongodb_connection,
)

__all__ = [
    "DEFAULT_CONVERSATIONS_COLLECTION",
    "DEFAULT_CONVERSATION_SUMMARIES_COLLECTION",
    "DEFAULT_MESSAGES_COLLECTION",
    "DEFAULT_MESSAGE_TRACES_COLLECTION",
    "DEFAULT_MESSAGE_TTS_USAGES_COLLECTION",
    "DEFAULT_MONGODB_DB_NAME",
    "DEFAULT_MONGODB_STARTUP_PING_ENABLED",
    "DEFAULT_MONGODB_TIMEOUT_MS",
    "DEFAULT_MONGODB_URI",
    "get_mongo_client",
    "get_mongo_database",
    "verify_mongodb_connection",
]
